#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [ "$(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l)" -eq 1 ]; then
    bspc monitor -d I II III IV V VI VII VIII IX X
else
    bspc monitor DP-3 -d I II III
    bspc monitor DP-1 -d IV V VI VII
    bspc monitor DP-2 -d VIII IX X
fi

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Fixes applications that start with only gray screen (Datagrip)
wmname LG3D

bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Code desktop='^2'
bspc rule -a brave desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
