#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

mainMonitor=eDP-1

noExternals=$(xrandr --listmonitors | cut -d' ' -f2 | head -n 1)
if [ "$noExternals" -eq 1 ]; then
    bspc monitor $mainMonitor -d 1 2 3 4 5 6 7 8 9 10
else
    bspc wm --reorder-monitors DP-1 HDMI-1 eDP-1
    bspc monitor DP-1   -d 1 2 3
    bspc monitor HDMI-1 -d 4 5 6 7
    bspc monitor $mainMonitor  -d 8 9 10
fi

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Fixes applications that start with only gray screen (Datagrip)
wmname LG3D

bspc rule -a Emacs state=tiled
bspc rule -a Peek state=floating
bspc rule -a mpv state=floating
bspc rule -a pentablet state=floating hidden=on
