VBoxClient-all &
/* xrandr -s 1920x1080 */
$HOME/dotfiles/scripts/3-mon-xps.sh
/* Replace the default X cursor */
xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill $HOME/dotfiles/misc/backgrounds/* --no-fehbg &
$HOME/.config/polybar/launch.sh
xcompmgr -c &
bspwm
